import assert from 'node:assert/strict';
import worker, {safeFailure,reportHealth} from './worker.mjs';
assert.deepEqual(safeFailure(new Error('Mail authentication failed: invalid_client (HTTP 401)')), {code:'invalid_client',http_status:401});
assert.deepEqual(safeFailure(new Error('secret-token-private')), {code:'runtime_failure'});
let saved, posted, failStorage=false;
const db={prepare(sql){return {bind(value){saved=value;return this;},async run(){if(failStorage)throw Error('DB unavailable');return {};},async first(){return {report:saved};}};}};
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{posted=JSON.parse(options.body);return {ok:true};};
await reportHealth({DB:db,ALERT_WEBHOOK_URL:'https://alerts.example.test'},'error',{code:'invalid_client'});
assert.equal(JSON.parse(saved).code,'invalid_client');
assert.equal(posted.code,'invalid_client');
failStorage=true;posted=null;
await reportHealth({DB:db,ALERT_WEBHOOK_URL:'https://alerts.example.test'},'error',{code:'runtime_failure'});
assert.equal(posted.code,'runtime_failure');
failStorage=false;
const unauthorized=await worker.fetch(new Request('https://worker.test/health'),{DB:db,CONTROLLER_TOKEN:'private'});
assert.equal(unauthorized.status,401);
globalThis.fetch=async()=>({ok:false,status:401,async json(){return {error:'invalid_client',error_description:'secret-token-private'};}});
await assert.rejects(()=>worker.scheduled({}, {DB:db,SEND_ENABLED:'true',GMAIL_CLIENT_ID:'private',GMAIL_CLIENT_SECRET:'private',GMAIL_REFRESH_TOKEN:'private',MAIL_FROM:'test@example.test'}),/invalid_client/);
assert.equal(JSON.parse(saved).code,'invalid_client');
assert.ok(!saved.includes('secret-token-private'));
globalThis.fetch=originalFetch;
console.log('PASS: classification, redaction, storage, independent alert, database failure fallback, endpoint authorization, scheduled OAuth failure');
